### ISSUE TITLE
leave jquery data fetching method out of leaflet advanced

### ISSUE THREAD

**Issue by ghost** [NieneB/Webmapping_for_beginners#5]
I would just demonstrate XMLHttpRequest as you already do. The description is very clear and it introduces a fundamental pattern for programming javascript in browsers: asynchronous programming. using jquery.getJSON follows the exact same pattern (asynchronous request with a callback function) and new programmers might think it's a fundamentally different thing they're doing when really it's just a convenience wrapper. There are tons of other libraries that provide such a helper function, jquery is just one (e.g. D3 provides one too), the sooner people learn what is happening under the hood the better.

**Comment by NieneB** [comment]
Added it to the description. Because, I am going to leave it in . Thanks!
